demo_dot_net-master/TicketingSystem/Controllers/MyRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using TicketingSystem.Models;

namespace TicketingSystem.Controllers
{
    public class MyRequestController : Controller
    {
        [HttpPost]
        public IActionResult MyRequest()
        {
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                string UserID = HttpContext.Session.GetString("UserID");
                ViewData["lblWelcome"] = "Welcome, " + UserID;
                MyRequestViewModel model = new MyRequestViewModel
                {
                    linkCaptions = PopulateTicketStatusHyperLinks(UserID),
                    listDetails = PopulateActivationRequestList("ALL", UserID)
                };
                HttpContext.Session.SetObjectAsJson("MY_REQUEST_MODEL", model);
                return View(model);
            }
            catch (Exception e)
            {
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View();
            }

        }

        [HttpGet]
        public IActionResult MyRequest(MyRequestViewModel model, string status)
        {
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                string UserID = HttpContext.Session.GetString("UserID");
                ViewData["lblWelcome"] = "Welcome, " + UserID;
                string sStatus = string.IsNullOrEmpty(status) ? "ALL" : status;
                model = new MyRequestViewModel
                {
                    linkCaptions = PopulateTicketStatusHyperLinks(UserID),
                    listDetails = PopulateActivationRequestList(sStatus, UserID)
                };
                HttpContext.Session.SetObjectAsJson("MY_REQUEST_MODEL", model);
                return View(model);
            }
            catch (Exception e)
            {
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View();
            }

        }

        private RequestLinkMasterModel PopulateTicketStatusHyperLinks(string sUserID)
        {
            RequestLinkMasterModel masterModel = new RequestLinkMasterModel();
            string sSQL = "SELECT IFNULL(COUNT(*), 0) AS TOTAL_COUNT, ";
            sSQL += "IFNULL(COUNT(CASE TICKET_STATUS WHEN 'OPEN' THEN 1 END), 0) AS OPEN_COUNT, ";
            sSQL += "IFNULL(COUNT(CASE TICKET_STATUS WHEN 'CLOSE' THEN 1 END), 0) AS CLOSE_COUNT, ";
            sSQL += "IFNULL(COUNT(CASE TICKET_STATUS WHEN 'ASSIGNED' THEN 1 END), 0) AS ASSIGNED_COUNT, ";
            sSQL += "IFNULL(COUNT(CASE TICKET_STATUS WHEN 'HOLD' THEN 1 END), 0) AS HOLD_COUNT, ";
            sSQL += "IFNULL(COUNT(CASE TICKET_STATUS WHEN 'REJECTED' THEN 1 END), 0) AS REJECTED_COUNT ";
            sSQL += "FROM TBL_ACTIVATION_REQ_MASTER WHERE TICKET_CREATE_USER = '" + sUserID + "';";

            MySqlConnection connection = new MySqlConnection(CustUtility.CONN_STR_SQL);
            try
            {
                MySqlCommand command = new MySqlCommand(sSQL);
                command.Connection = connection;
                connection.Open();
                MySqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    masterModel.reqTotalLinkCaption = "Your Total Request count is " + reader["TOTAL_COUNT"].ToString();
                    masterModel.reqOpenLinkCaption = "You have " + reader["OPEN_COUNT"].ToString() + " Open Requests";
                    masterModel.reqCloseLinkCaption = "You have " + reader["CLOSE_COUNT"].ToString() + " Close Requests";
                    masterModel.reqAssignLinkCaption = "You have " + reader["ASSIGNED_COUNT"].ToString() + " Assigned Requests";
                    masterModel.reqHoldLinkCaption = "You have " + reader["HOLD_COUNT"].ToString() + " Hold Requests";
                    masterModel.reqRejectLinkCaption = "You have " + reader["REJECTED_COUNT"].ToString() + " Rejected Requests";
                }
            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                if (connection != null)
                {
                    connection.Close();
                }
                connection = null;
            }
            return masterModel;
        }

        private List<RequestDetailsMaster> PopulateActivationRequestList(string sTicketStatus, string sUserID)
        {
            List<RequestDetailsMaster> requests = new List<RequestDetailsMaster>();
            string sSQL;
            sSQL = "SELECT TICKET_CREATE_DATE 'REQUEST_DATE', TICKET_NO 'TICKET_NO', ";
            sSQL += "SERVICE_NAME 'SERVICE_NAME', TICKET_STATUS 'TICKET_STATUS', ";
            sSQL += "TICKET_ASSIGN_USER 'TICKET_ASSIGN_USER', ACTIVATION_TEAM 'ACTIVATION_TEAM', ";
            sSQL += "COMMENTS 'COMMENTS' ";
            sSQL += "FROM TBL_ACTIVATION_REQ_MASTER ";
            sSQL += "WHERE TICKET_CREATE_USER = '" + sUserID + "' ";
            if (sTicketStatus != "ALL")
            {
                sSQL += "AND TICKET_STATUS = '" + sTicketStatus + "' ";
            }
            sSQL += "ORDER BY TICKET_CREATE_DATE DESC";
            MySqlConnection connection = new MySqlConnection(CustUtility.CONN_STR_SQL);
            try
            {
                MySqlCommand command = new MySqlCommand(sSQL);
                command.Connection = connection;
                connection.Open();
                MySqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    RequestDetailsMaster details = new RequestDetailsMaster
                    {
                        requestDate = reader["REQUEST_DATE"].ToString(),
                        ticketId = reader["TICKET_NO"].ToString(),
                        serviceName = reader["SERVICE_NAME"].ToString(),
                        status = reader["TICKET_STATUS"].ToString(),
                        ticketAssignedUser = reader["TICKET_ASSIGN_USER"].ToString(),
                        responsibleTeam = reader["ACTIVATION_TEAM"].ToString(),
                        comments = reader["COMMENTS"].ToString()
                    };
                    requests.Add(details);
                }
            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                if (connection != null)
                {
                    connection.Close();
                }
                connection = null;
            }
            return requests;
        }

        public IActionResult Btn_ActRequest()
        {
            return RedirectToAction("ActRequest", "ActivationRequest");
        }

        public IActionResult Btn_MyTicket()
        {
            return RedirectToAction("MyTicket", "SearchMyTicket");
        }

        public IActionResult Btn_ActivationDashboard()
        {
            return RedirectToAction("Dashboard", "ActivationDashboard");
        }
    }
}

demo_dot_net-master/TicketingSystem/Controllers/SearchAllTicketController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using TicketingSystem.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Cors;

namespace TicketingSystem.Controllers
{
    public class SearchAllTicketController : Controller
    {
        [HttpPost]
        public IActionResult AllTicket()
        {
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                ViewData["lblWelcome"] = "Welcome, " + HttpContext.Session.GetString("UserID");
                SearchAllTicketModel searchAllTicketModel = new SearchAllTicketModel
                {
                    executor = PopulateExecutorList(UserInfo.txtUserGroup),
                    channel = PopulateChannelList(UserInfo.txtUserGroup),
                    service = PopulateServiceList(UserInfo.txtUserGroup),
                    ticketStatus = CustUtility.PopulateTicketStatusList(),
                    urgent = CustUtility.PopulateUrgentList(),
                    product= new List<SelectListItem>()
                };
                HttpContext.Session.SetObjectAsJson("sAllTicketModel", searchAllTicketModel);
                return View(searchAllTicketModel);
            }
            catch (Exception e)
            {
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View();
            }
        }
        [HttpPost]
        public IActionResult AllTicketSearch(SearchAllTicketModel searchAllTicketModel)
        {
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                ViewData["lblWelcome"] = "Welcome, " + HttpContext.Session.GetString("UserID");
                searchAllTicketModel.listReqMaster = this.btnSearch_Click(UserInfo.txtUserGroup, searchAllTicketModel.txtRequestDateFrom, searchAllTicketModel.txtRequestDateTo, searchAllTicketModel.ddlExecutor, searchAllTicketModel.ddlProduct, searchAllTicketModel.ddlChannelType, searchAllTicketModel.ddlService, searchAllTicketModel.ddlTicketStatus, searchAllTicketModel.ddlUrgent, searchAllTicketModel.txtTicketNo);
                var SessionSearchAllTicket = HttpContext.Session.GetObjectFromJson<SearchAllTicketModel>("sAllTicketModel");
                searchAllTicketModel.service = SessionSearchAllTicket.service;
                searchAllTicketModel.channel = SessionSearchAllTicket.channel;
                searchAllTicketModel.executor = SessionSearchAllTicket.executor;
                searchAllTicketModel.ticketStatus = SessionSearchAllTicket.ticketStatus;
                searchAllTicketModel.urgent = SessionSearchAllTicket.urgent;
                var varProductList = HttpContext.Session.GetObjectFromJson<List<SelectListItem>>("sProductList");
                if(varProductList != null && !String.IsNullOrEmpty(searchAllTicketModel.ddlService))
                {
                    searchAllTicketModel.product = varProductList;
                }
                else
                {
                    searchAllTicketModel.product = new List<SelectListItem>();
                }
                
                return View("AllTicket", searchAllTicketModel);
            }
            catch (Exception e)
            {
                
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View("AllTicket", searchAllTicketModel);
            }
        }
        public IActionResult btnActivationDashboard_Click()
        {
            return RedirectToAction("Dashboard", "ActivationDashboard");
        }
        [HttpGet]
        [EnableCors("AllowOrigin")]
        public JsonResult GetProductList(String ServiceName)
        {
            List<SelectListItem> productList =PopulateProductList(ServiceName);
            HttpContext.Session.SetObjectAsJson("sProductList", productList);
           /* var SessionSearchAllTicket = HttpContext.Session.GetObjectFromJson<SearchAllTicketModel>("AllTicketModel");
            SessionSearchAllTicket.product = productList;
            HttpContext.Session.SetObjectAsJson("AllTicketModel", SessionSearchAllTicket);*/
            return Json(productList);
        }

        private List<SelectListItem> PopulateServiceList(string sUserGroup)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            using (MySqlConnection con = new MySqlConnection(CustUtility.CONN_STR_SQL))
            {
                string sSQL = "SELECT ID,SERVICE_NAME FROM TBL_LIST_SERVICE WHERE ACTIVATION_TEAM = '" + sUserGroup + "'";
                using (MySqlCommand cmd = new MySqlCommand(sSQL))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr["SERVICE_NAME"].ToString(),
                                Value = sdr["SERVICE_NAME"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }
            return items;
        }
        private List<SelectListItem> PopulateChannelList(string sUserGroup)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            using (MySqlConnection con = new MySqlConnection(CustUtility.CONN_STR_SQL))
            {
                string sSQL = "SELECT ID,CHANNEL_TYPE FROM TBL_LIST_CHANNEL_TYPE WHERE ACTIVATION_TEAM = '" + sUserGroup + "'";
                using (MySqlCommand cmd = new MySqlCommand(sSQL))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr["CHANNEL_TYPE"].ToString(),
                                Value = sdr["CHANNEL_TYPE"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }
            return items;
        }
        private List<SelectListItem> PopulateExecutorList(string sUserGroup)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            using (MySqlConnection con = new MySqlConnection(CustUtility.CONN_STR_SQL))
            {
                string sSQL = "SELECT USER_ID FROM TBL_USER WHERE USER_GROUP = '" + sUserGroup + "'";
                using (MySqlCommand cmd = new MySqlCommand(sSQL))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr["USER_ID"].ToString(),
                                Value = sdr["USER_ID"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }
            return items;
        }
        private List<SelectListItem> PopulateProductList(string ServiceName)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            using (MySqlConnection con = new MySqlConnection(CustUtility.CONN_STR_SQL))
            {
                string sSQL = "SELECT PRODUCT_NAME FROM TBL_LIST_PRODUCT ";
                sSQL += "WHERE SERVICE_NAME = '" + ServiceName + "'";
                using (MySqlCommand cmd = new MySqlCommand(sSQL))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr["PRODUCT_NAME"].ToString(),
                                Value = sdr["PRODUCT_NAME"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }
            return items;
        }        
        private List<ActivationReqMasterModel> btnSearch_Click(string sUserGroup, string txtExecutionDateFrom, string txtExecutionDateTo, string selectedExecutor, string selectedProduct, string selectedChannel, string selectedService, string selectedStatus, string selectedUrgent, string txtTicketNo)
        {
            List<ActivationReqMasterModel> list = new List<ActivationReqMasterModel>();
            using (MySqlConnection con = new MySqlConnection(CustUtility.CONN_STR_SQL))
                try
                {
                    string sSQL;
                    string sReqDateFrom, sReqDateTo;
                    string sExecDateTo = Convert.ToDateTime(txtExecutionDateTo).AddDays(1).ToString("yyyy-MM-dd");
                    sSQL = "SELECT TICKET_CREATE_DATE 'REQUEST_DATE', TICKET_NO 'TICKET_NO', ";
                    sSQL += "SERVICE_NAME 'SERVICE_NAME', PRODUCT_NAME 'PRODUCT_NAME', IS_URGENT 'URGENT', ";

demo_dot_net-master/TicketingSystem/Views/SearchAllTicket/AllTicket.cshtml
@model TicketingSystem.Models.SearchAllTicketModel
    <form method="post">
        <table width="100%">
            <tr>
                <td align="right" colspan="4">
                    <span id="_lblWelcome">@ViewData["lblWelcome"]</span>
                </td>
            </tr>
            @if (@ViewData["lblMessage"] != null)
            {
                <tr>
                    <td align="center" colspan="4">
                        <span id="lblMessage" style="color:Red;background-color:LightSteelBlue;font-weight:bold;text-align: center; padding-left:20px; padding-right:20px;">@ViewData["lblMessage"]</span>
                    </td>
                </tr>            
             }
        </table>
        <table width="100%">
            <tr>
                <td colspan="4" align="left" style="background-color: Black; height: 30px">
                    <span id="lblPageTitle" style="color:White;font-size:Large;font-weight:bold;">Search Ticket</span>
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    <input type="submit" asp-controller="MyRequest" asp-action="MyRequest" value="My Requests" class="menuButton" />
                    <input type="submit" asp-controller="SearchAllTicket" asp-action="btnActivationDashboard_Click" value="Activation Dashboard" class="menuButton" />
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    <fieldset>
                        <legend><font face="Verdana" size="2"><strong style="padding-bottom: 10px">Search Criteria</strong></font></legend>
                        <table width="80%">
                            <tr>
                                <td colspan="4" style="height: 5px" class="leftCell">
                                    &nbsp;
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 20%; height: 20px;" class="leftCell">
                                    Request Date From:
                                </td>
                                <td style="width: 30%; height: 20px;" class="rightCell">
                                    <input type="text" id="datepicker" name="txtRequestDateFrom" value="@Model.txtRequestDateFrom">
                                </td>
                                <td style="width: 20%; height: 20px;" class="leftCell">
                                    Request Date To:
                                </td>
                                <td style="width: 30%; height: 20px;" class="rightCell">
                                    <input type="text" id="datepicker1" name="txtRequestDateTo" value="@Model.txtRequestDateTo">
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 20%" class="leftCell">
                                    Service Name:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    @Html.DropDownListFor(m => m.ddlService, Model.service, "Please select ...", new { style = "width: 240px;" })
                                </td>
                                <td style="width: 20%" class="leftCell">
                                    Product Name:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    @Html.DropDownListFor(m => m.ddlProduct, Model.product, "Please select ...", new { style = "width: 240px;" })                                    
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 20%" class="leftCell">
                                    Executor Name:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    @Html.DropDownListFor(m => m.ddlExecutor, Model.executor, "Please select ...", new { style = "width: 240px;" })
                                </td>
                                <td style="width: 20%" class="leftCell">
                                    Ticket Status:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    @Html.DropDownListFor(m => m.ddlTicketStatus, Model.ticketStatus, "Please select ...", new { style = "width: 150px;" })
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 20%" class="leftCell">
                                    Channel Type:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    @Html.DropDownListFor(m => m.ddlChannelType, Model.channel, "Please select ...", new { style = "width: 240px;" })
                                </td>
                                <td style="width: 20%" class="leftCell">
                                    Urgent:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    @Html.DropDownListFor(m => m.ddlUrgent, Model.urgent, "Please select ...", new { style = "width: 150px;" })
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 20%" class="leftCell">
                                    Ticket #:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    <input type="text" id="txtTicketNo" name="txtTicketNo" style="width:120px;" value="@Model.txtTicketNo">
                                </td>
                                <td style="width: 20%" class="leftCell">
                                    &nbsp;
                                </td>
                                <td style="width: 30%" class="leftCell">
                                    &nbsp;
                                </td>
                            </tr>
                            <tr>
                                <td colspan="4" align="center" valign="middle" style="height: 35px">
                                    <input type="submit" asp-controller="SearchAllTicket" asp-action="AllTicketSearch" value="Search" style="width:100px;" />
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                    <br />
                    <fieldset>
                        <legend><font face="Verdana" size="2"><strong style="padding-bottom: 10px">Search Result</strong></font></legend>
                        <br />
                        <div>
                            @if (Model.listReqMaster != null && Model.listReqMaster.Any())
                            {
                <table cellspacing="0" rules="all" border="1" id="gvActivationRequest" style="width:90%;border-collapse:collapse;">
                    <tr style="background-color:#CCE4F5;font-weight:bold;height:20px;">
                        <th scope="col">Request Date</th>
                        <th scope="col">Ticket #</th>
                        <th scope="col">Service Name</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Urgent</th>
                        <th scope="col">Status</th>
                        <th scope="col">Requester</th>
                        <th scope="col">Assigned User</th>
                    </tr>
                    @foreach (ActivationReqMasterModel activationReq in Model.listReqMaster)
                    {
                        <tr style="color:Black;height:18px;">
                            <td>
                                <span id="" style="display:inline-block;width:75px;">@activationReq.ticketCreateDate</span>
                            </td>
                            <td style="white-space:nowrap;">
                                <a id="" href="/ActivationExecution/Execution?reqticketno=@activationReq.ticketNo" style="display:inline-block;width:110px;" target="_blank">@activationReq.ticketNo</a>
                            </td>
                            <td>
                                <span id="" style="display:inline-block;width:120px;">@activationReq.serviceName</span>
                            </td>
                            <td>
                                <span id="" style="display:inline-block;width:120px;">@activationReq.productName</span>
                            </td>
                            <td style="white-space:nowrap;">
                                <span id="" style="display:inline-block;width:50px;">@activationReq.isUrgent</span>
                            </td>
                            <td style="white-space:nowrap;">
                                <span id="" style="display:inline-block;width:80px;">@activationReq.ticketStatus</span>
                            </td>
                            <td>
                                <span id="" style="display:inline-block;width:100px;">@activationReq.ticketCreateUser</span>
                            </td>
                            <td>
                                <span id="" style="display:inline-block;width:100px;">@activationReq.ticketAssignUser</span>
                            </td>
                        </tr>
                    }
                </table>
                }
                        </div>
                        <br />
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    &nbsp;
                </td>
            </tr>
        </table>
        <script type="text/javascript">
            //Bind City dropdownlist
            $("#ddlService").change(function () {
                var ddlService = $("#ddlService").val();
                var url = '/SearchAllTicket/GetProductList';
                $.getJSON(url, { ServiceName: ddlService }, function (data) {
                    var item = "<option value=''>Please select ...</option>";
                    $("#ddlProduct").empty();
                    $.each(data, function (i, product) {
                        item += '<option value="' + product.value + '">' + product.text + '</option>'
                    });
                    $("#ddlProduct").html(item);
                });
            });
        </script>
    </form>