demo_dot_net-master/TicketingSystem/Models/UserManagementViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketingSystem.Models
{
    public class UserManagementViewModel
    {
        public string selectedUser { get; set; }
        public List<SelectListItem> userList { get; set; }
        public string selectedDh { get; set; }
        public List<SelectListItem> dhList { get; set; }
        public UserDetailsMasterModel userDetails { get; set; }
    }
}

demo_dot_net-master/TicketingSystem/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Server.HttpSys;
using MySql.Data.MySqlClient;
using TicketingSystem.Models;

namespace TicketingSystem.Controllers
{
    public class UserManagementController : Controller
    {
        [HttpPost]
        public IActionResult UserMgt()
        {
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                ViewData["lblWelcome"] = "Welcome, " + HttpContext.Session.GetString("UserID");
                UserManagementViewModel model = new UserManagementViewModel
                {
                    userList = PopulateUserList(),
                    dhList = PopulateDhList(),
                    userDetails = new UserDetailsMasterModel
                    {
                        userName = "",
                        userId = "",
                        createdOn = "",
                        dhName = "Please select ..."
                    }
                };
                HttpContext.Session.SetObjectAsJson("USER_MGT", model);
                ViewData["Password"] = "";
                ViewData["txtUserId_Enabled"] = "enabled";
                ViewData["btnCreate_Enabled"] = "enabled";
                ViewData["btnUpdate_Enabled"] = "disabled";
                ViewData["btnDelete_Enabled"] = "disabled";
                return View(model);
            }
            catch (Exception e)
            {
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View();
            }
        }

        private List<SelectListItem> PopulateUserList()
        {
            List<SelectListItem> itemList = new List<SelectListItem>();
            string sSQL;
            sSQL = "SELECT USER_NAME FROM TBL_USER_DH;";
            MySqlConnection connection = new MySqlConnection(CustUtility.CONN_STR_SQL);
            try
            {
                MySqlCommand command = new MySqlCommand(sSQL);
                command.Connection = connection;
                connection.Open();
                MySqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    SelectListItem item = new SelectListItem
                    {
                        Text = reader["USER_NAME"].ToString(),
                        Value = reader["USER_NAME"].ToString()
                    };
                    itemList.Add(item);
                }
            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                if (connection != null)
                {
                    connection.Close();
                }
                connection = null;
            }
            return itemList;
        }

        private List<SelectListItem> PopulateDhList()
        {
            List<SelectListItem> itemList = new List<SelectListItem>();
            string sSQL;
            sSQL = "SELECT CHANNEL_NAME FROM TBL_LIST_CHANNEL WHERE CHANNEL_TYPE='Distribution House' ORDER BY CHANNEL_NAME;";
            MySqlConnection connection = new MySqlConnection(CustUtility.CONN_STR_SQL);
            try
            {
                MySqlCommand command = new MySqlCommand(sSQL);
                command.Connection = connection;
                connection.Open();
                MySqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    SelectListItem item = new SelectListItem
                    {
                        Text = reader["CHANNEL_NAME"].ToString(),
                        Value = reader["CHANNEL_NAME"].ToString()
                    };
                    itemList.Add(item);
                }
            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                if (connection != null)
                {
                    connection.Close();
                }
                connection = null;
            }
            return itemList;
        }

        [HttpPost]
        public ActionResult UserChange(UserManagementViewModel model)
        {
            ViewData["txtUserId_Enabled"] = "disabled";
            ViewData["btnCreate_Enabled"] = "disabled";
            ViewData["btnUpdate_Enabled"] = "enabled";
            ViewData["btnDelete_Enabled"] = "enabled";
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                ViewData["lblWelcome"] = "Welcome, " + HttpContext.Session.GetString("UserID");
                var SessionUserMgt = HttpContext.Session.GetObjectFromJson<UserManagementViewModel>("USER_MGT");
                model.userList = SessionUserMgt.userList;
                model.userDetails = GetUserDetails(model.selectedUser);
                model.dhList = SessionUserMgt.dhList;
                HttpContext.Session.SetObjectAsJson("USER_MGT", model);
                ViewData["Password"] = "";
                return View("UserMgt", model);
            }
            catch (Exception e)
            {
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View();
            }
        }

        private UserDetailsMasterModel GetUserDetails(string UserID)
        {
            UserDetailsMasterModel master = new UserDetailsMasterModel();
            string sSQL;
            sSQL = "SELECT * FROM TBL_USER_DH ";
            sSQL += "WHERE USER_NAME = '" + UserID + "';";
            MySqlConnection connection = new MySqlConnection(CustUtility.CONN_STR_SQL);
            try
            {
                MySqlCommand command = new MySqlCommand(sSQL);
                command.Connection = connection;
                connection.Open();
                MySqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    master.userName = reader["USER_NAME"].ToString();
                    master.userId = reader["USER_ID"].ToString();
                    master.createdOn = Convert.ToDateTime(reader["CREATED_ON"].ToString()).ToString("dd - MMM - yyyy hh: mm:ss tt");
                    master.dhName = reader["DH_NAME"].ToString();
                }
            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                if (connection != null)
                {
                    connection.Close();
                }
                connection = null;
            }
            return master;
        }

        [HttpPost]
        public IActionResult BtnReset_Click(UserManagementViewModel model)
        {
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                ViewData["lblWelcome"] = "Welcome, " + HttpContext.Session.GetString("UserID");
                model.userList = PopulateUserList();
                model.dhList = PopulateDhList();
                model.userDetails = new UserDetailsMasterModel
                {
                    userName = "",
                    userId = "",
                    createdOn = "",
                    dhName = "Please select ..."
                };
                model.selectedUser = "";
                model.selectedDh = "";
                HttpContext.Session.SetObjectAsJson("USER_MGT", model);
                ViewData["Password"] = "";
                ViewData["txtUserId_Enabled"] = "enabled";
                ViewData["btnCreate_Enabled"] = "enabled";
                ViewData["btnUpdate_Enabled"] = "disabled";
                ViewData["btnDelete_Enabled"] = "disabled";
                return View("UserMgt", model);
            }
            catch (Exception e)
            {
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View("UserMgt", model);
            }
        }

        [HttpPost]
        public IActionResult BtnUpdate_Click(UserManagementViewModel model, string txtUserName, string txtUserId)
        {
            string UpdatedBy = HttpContext.Session.GetString("UserID");
            ViewData["Password"] = "";
            ViewData["txtUserId_Enabled"] = "enabled";
            ViewData["btnCreate_Enabled"] = "disabled";
            ViewData["btnUpdate_Enabled"] = "enabled";
            ViewData["btnDelete_Enabled"] = "enabled";
            var SessionUserMgt = HttpContext.Session.GetObjectFromJson<UserManagementViewModel>("USER_MGT");
            if (string.IsNullOrEmpty(txtUserName) && string.IsNullOrEmpty(txtUserId))
            {
                ViewData["lblMessage"] = "ERROR: " + "UserName and UserID is required!!";
                model.userList = SessionUserMgt.userList;
                model.dhList = SessionUserMgt.dhList;
                model.userDetails = SessionUserMgt.userDetails;
                return View("UserMgt", model);
            }

            if (string.IsNullOrEmpty(model.selectedDh) && !string.IsNullOrEmpty(txtUserName))
            {
                try

demo_dot_net-master/TicketingSystem/Views/UserManagement/UserMgt.cshtml
@model UserManagementViewModel
<form method="post" action="@Url.Action("UserChange", "UserManagement")">
    <table width="100%">
        <tr>
            <td align="right" colspan="4">
                <span id="lblWelcome">@ViewData["lblWelcome"]</span>
            </td>
        </tr>
        @if (@ViewData["lblMessage"] != null)
        {
            <tr>
                <td align="center" colspan="4">
                    <span id="lblMessage" style="color:Red;background-color:LightSteelBlue;font-weight:bold;text-align: center; padding-left:20px; padding-right:20px;">@ViewData["lblMessage"]</span>
                </td>
            </tr>
        }
    </table>
    <table width="100%">
        <tr>
            <td colspan="4" align="left" style="background-color: Black; height: 30px">
                <span id="lblPageTitle" style="color:White;font-size:Large;font-weight:bold;">User Management</span>
            </td>
        </tr>
        <tr>
            <td align="left" colspan="4">
                &nbsp;
            </td>
        </tr>
        <tr>
            <td align="left" colspan="4">
                <input type="submit" asp-controller="UserManagement" asp-action="Btn_MyRequest" value="My Requests" class="menuButton" style="width:140px" />
                <input type="submit" asp-controller="UserManagement" asp-action="Btn_Dashboard" value="Activation Dashboard" class="menuButton" style="width:140px" />
                <input type="submit" asp-controller="UserManagement" asp-action="Btn_Management" value="Channel Management" class="menuButton" style="width:140px" />
            </td>
        </tr>
        <tr>
            <td align="left" colspan="4">
                &nbsp;
            </td>
        </tr>
        <tr>
            <td align="left" colspan="4">
                <fieldset>
                    <legend><font face="Verdana" size="2"><strong style="padding-bottom: 10px">Search Criteria</strong></font></legend>
                    <table width="80%">
                        <tr>
                            <td colspan="4" style="height: 5px" class="leftCell">
                                &nbsp;
                            </td>
                        </tr>

                        <tr>
                            <td style="width: 20%" class="leftCell">
                                User:
                            </td>
                            <td style="width: 80%" class="rightCell">
                                <span style="width:260px" id="ddlUserList">
                                    @Html.DropDownListFor(ddl => ddl.selectedUser, Model.userList, "Please select ...", new { style = "width: 260px", onchange = "this.form.submit()" })
                                </span>
                            </td>

                        </tr>

                        <tr>
                            <td style="width: 20%" class="leftCell">
                                &nbsp;
                            </td>
                            <td style="width: 80%" class="leftCell">
                                &nbsp;
                            </td>
                        </tr>

                        <tr>
                            <td style="width: 20%" class="leftCell">
                                Distribution House:
                            </td>
                            <td style="width: 80%" class="rightCell">
                                <span style="width:260px" id="ddlDH">
                                    @Html.DropDownListFor(ddl => ddl.userDetails.dhName, Model.dhList, "Please select ...", new { style = "width: 260px" })
                                </span>
                            </td>
                        </tr>

                        <tr>
                            <td style="width: 20%" class="leftCell">
                                User Name:
                            </td>
                            <td style="width: 80%" class="rightCell">
                                <input type="text" id="txtUserName" name="txtUserName" style="width:159px; height:21px" value="@Model.userDetails.userName" />
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 20%" class="leftCell">
                                User ID:
                            </td>
                            <td style="width: 80%" class="rightCell">
                                @if (!string.IsNullOrEmpty(ViewData["txtUserId_Enabled"].ToString()) && ViewData["txtUserId_Enabled"].ToString().Equals("disabled"))
                                {
                                    <input type="text" id="txtUserId" name="txtUserId" style="width:160px" value="@Model.userDetails.userId" disabled />
                                }
                                else
                                {
                                    <input type="text" id="txtUserId" name="txtUserId" style="width:160px" value="@Model.userDetails.userId" />
                                } &nbsp; &nbsp; &nbsp; &nbsp;
                                <span id="lblPassword">@ViewData["Password"].ToString()</span>
                                <input type="submit" id="btn_passReset" value="Reset Password" asp-controller="UserManagement" asp-action="btn_passReset_Click" />
                            </td>

                        </tr>

                        <tr>
                            <td style="width: 20%" class="leftCell">
                                Created By:
                            </td>
                            <td style="width: 80%" class="rightCell">
                                <input type="text" id="txtCreatedBy" name="txtCreatedBy" style="width:159px" value="@Model.userDetails.userName" disabled />

                            </td>

                        </tr>
                        <tr>
                            <td style="width: 40%" class="leftCell">
                                Created On:
                            </td>
                            <td style="width: 80%" class="rightCell">
                                <input type="text" id="txtCreatedOn" name="txtCreatedOn" style="width:159px" value="@Model.userDetails.createdOn" disabled />
                            </td>

                        </tr>
                        <tr>
                            <td colspan="2" align="right" valign="middle" style="height: 35px">
                                <input type="submit" id="btnReset" value="Reset" style="width:100px" asp-action="BtnReset_Click" />
                                @if (!string.IsNullOrEmpty(ViewData["btnCreate_Enabled"].ToString()) && ViewData["btnCreate_Enabled"].ToString().Equals("disabled"))
                                {
                                    <input type="submit" id="btnCreate" value="Create" style="width:100px" asp-action="BtnCreate_Click" disabled />
                                }
                                else
                                {
                                    <input type="submit" id="btnCreate" value="Create" style="width:100px" asp-action="BtnCreate_Click" />
                                }
                                @if (!string.IsNullOrEmpty(ViewData["btnUpdate_Enabled"].ToString()) && ViewData["btnUpdate_Enabled"].ToString().Equals("disabled"))
                                {
                                    <input type="submit" id="btnUpdate" value="Update" style="width:100px" asp-action="BtnUpdate_Click" disabled />
                                }
                                else
                                {
                                    <input type="submit" id="btnUpdate" value="Update" style="width:100px" asp-action="BtnUpdate_Click" />
                                }
                                @if (!string.IsNullOrEmpty(ViewData["btnDelete_Enabled"].ToString()) && ViewData["btnDelete_Enabled"].ToString().Equals("disabled"))
                                {
                                    <input type="submit" id="btnDelete" value="Delete" style="width:100px" asp-action="BtnDelete_Click" disabled />
                                }
                                else
                                {
                                    <input type="submit" id="btnDelete" value="Delete" style="width:100px" asp-action="BtnDelete_Click" />
                                }
                            </td>

                        </tr>
                    </table>
                </fieldset>
                <br />

            </td>
        </tr>
        <tr>
            <td align="left" colspan="4">
                &nbsp;
            </td>
        </tr>
    </table>
</form>