demo_dot_net-master/TicketingSystem/Controllers/SearchMyTicketController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using TicketingSystem.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using MySqlX.XDevAPI;

namespace TicketingSystem.Controllers
{
    public class SearchMyTicketController : Controller
    {
        [HttpPost]
        public IActionResult MyTicket()
        {
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                ViewData["lblWelcome"] = "Welcome, " + HttpContext.Session.GetString("UserID");
                SearchMyTicketModel searchMyTicketModel = new SearchMyTicketModel
                {
                    ticketStatus = CustUtility.PopulateTicketStatusList()
                };
                return View(searchMyTicketModel);
            }
            catch (Exception e)
            {
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View();
            }
        }
        [HttpPost]
        public IActionResult MyTicketSearch(SearchMyTicketModel mymodel)
        {
            try
            {
                var UserInfo = HttpContext.Session.GetObjectFromJson<UserModel>("UserInfo");
                if (UserInfo == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                ViewData["lblWelcome"] = "Welcome, " + HttpContext.Session.GetString("UserID");
                mymodel.reqMstList = this.btnSearch_Click(mymodel.txtRequestDateTo,mymodel.txtRequestDateFrom,mymodel.ddlTicketStatus,mymodel.txtTicketNo);
                mymodel.ticketStatus = CustUtility.PopulateTicketStatusList();
                return View("MyTicket", mymodel);
            }
            catch (Exception e)
            {
                ViewData["lblMessage"] = "ERROR: " + e.Message;
                return View("MyTicket", mymodel);
            }
        }
        private List<ActivationReqMasterModel> btnSearch_Click(string txtExecutionDateTo, string txtExecutionDateFrom, string selectedStatus, string txtTicketNo)
        {
            List<ActivationReqMasterModel> list = new List<ActivationReqMasterModel>();
            MySqlConnection con = new MySqlConnection(CustUtility.CONN_STR_SQL);
                try
                {
                    string sSQL;
                    string sReqDateFrom, sReqDateTo;
                    string sSearchType = "OWN_TICKET";
                    string sUserID = HttpContext.Session.GetString("UserID");

                    sSQL = "SELECT TICKET_CREATE_DATE 'REQUEST_DATE', TICKET_NO 'TICKET_NO', ";
                    sSQL += "SERVICE_NAME 'SERVICE_NAME', TICKET_STATUS 'TICKET_STATUS', ";
                    sSQL += "TICKET_ASSIGN_USER 'ASSIGNED_USER', ACTIVATION_TEAM 'ACTIVATION_TEAM', ";
                    sSQL += "COMMENTS 'COMMENTS' ";
                    sSQL += "FROM TBL_ACTIVATION_REQ_MASTER ";
                    sSQL += "WHERE 1 = 1 ";
                    if (!String.IsNullOrEmpty(txtTicketNo))
                    {
                        sSQL += "AND TICKET_NO = '" + txtTicketNo + "' ";
                        sSearchType = "OTHERS_TICKET";
                    }
                    if (!String.IsNullOrEmpty(selectedStatus))
                    {
                        sSQL += "AND TICKET_STATUS = '" + selectedStatus + "' ";
                    sSearchType = "OWN_TICKET";
                    }
                    if (!String.IsNullOrEmpty(txtExecutionDateTo) && !String.IsNullOrEmpty(txtExecutionDateFrom))
                    {
                        sReqDateFrom = Convert.ToDateTime(txtExecutionDateFrom).ToString("yyyy-MM-dd");
                        sReqDateTo = Convert.ToDateTime(txtExecutionDateTo).AddDays(1).ToString("yyyy-MM-dd");
                        sSQL += "AND TICKET_CREATE_DATE >= '" + sReqDateFrom + "' AND TICKET_CREATE_DATE < '" + sReqDateTo + "' ";
                        sSearchType = "OWN_TICKET";
                    }
                    if (sSearchType == "OWN_TICKET")
                    {
                        sSQL += "AND TICKET_CREATE_USER = '" + sUserID + "' ";
                    }
                    sSQL += "ORDER BY TICKET_CREATE_DATE DESC";

                    MySqlCommand cmd = new MySqlCommand(sSQL);
                    cmd.Connection = con;
                    con.Open();
                    MySqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        ActivationReqMasterModel reqMaster = new ActivationReqMasterModel{
                            ticketCreateDate = sdr["REQUEST_DATE"].ToString(),
                            ticketNo = sdr["TICKET_NO"].ToString(),
                            serviceName = sdr["SERVICE_NAME"].ToString(),
                            ticketStatus = sdr["TICKET_STATUS"].ToString(),
                            ticketAssignUser = sdr["ASSIGNED_USER"].ToString(),
                            activationTeam= sdr["ACTIVATION_TEAM"].ToString(),
                            comments = sdr["COMMENTS"].ToString(),
                        };
                        list.Add(reqMaster);
                    }
                }
                catch (Exception ex)
                {
                    string s = ex.Message;
                    throw;
                }
                finally
                {
                    con.Close();
                }
            return list;
        }
        public IActionResult Btn_MyRequest()
        {
            return RedirectToAction("MyRequest", "MyRequest");
        }

    }
}

demo_dot_net-master/TicketingSystem/Views/SearchMyTicket/MyTicket.cshtml
@model TicketingSystem.Models.SearchMyTicketModel
<form method="post">
        <table width="100%">
            <tr>
                <td align="right" colspan="4">
                    <span id="_lblWelcome">@ViewData["lblWelcome"]</span>
                </td>
            </tr>
            @if (@ViewData["lblMessage"] != null)
            {
                <tr>
                    <td align="center" colspan="4">
                        <span id="lblMessage" style="color:Red;background-color:LightSteelBlue;font-weight:bold;text-align: center; padding-left:20px; padding-right:20px;">@ViewData["lblMessage"]</span>
                    </td>
                </tr>
            }
        </table>
        <table width="100%">
            <tr>
                <td colspan="4" align="left" style="background-color: Black; height: 30px">
                    <span id="_lblPageTitle" style="color:White;font-size:Large;font-weight:bold;">Search My Ticket</span>
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    <input type="submit" asp-controller="SearchMyTicket" asp-action="Btn_MyRequest" value="My Requests" class="menuButton" />
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    <fieldset>
                        <legend><font face="Verdana" size="2"><strong style="padding-bottom: 10px">Search Criteria</strong></font></legend>
                        <table width="70%">
                            <tr>
                                <td colspan="4" style="height: 5px" class="leftCell">
                                    &nbsp;
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 20%; height: 20px;" class="leftCell">
                                    Request Date From:
                                </td>
                                <td style="width: 30%; height: 20px;" class="rightCell">
                                    <input type="text" id="datepicker" name="txtRequestDateFrom" value="@Model.txtRequestDateFrom">
                                </td>
                                <td style="width: 20%; height: 20px;" class="leftCell">
                                    Request Date To:
                                </td>
                                <td style="width: 30%; height: 20px;" class="rightCell">
                                    <input type="text" id="datepicker1" name="txtRequestDateTo" value="@Model.txtRequestDateTo">
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 20%" class="leftCell">
                                    Ticket Status:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    @Html.DropDownListFor(m => m.ddlTicketStatus, Model.ticketStatus, "Please select ...", new { style = "width: 150px;" })                                    
                                </td>
                                <td style="width: 20%" class="leftCell">
                                    Ticket #:
                                </td>
                                <td style="width: 30%" class="rightCell">
                                    <input type="text" id="txtTicketNo" name="txtTicketNo" value="@Model.txtTicketNo" style="width:120px;">
                                </td>
                            </tr>
                            <tr>
                                <td colspan="4" align="center" valign="middle" style="height: 35px">
                                    <input type="submit" asp-controller="SearchMyTicket" asp-action="MyTicketSearch" value="Search" style="width:100px;"/>
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                    <br />
                    <fieldset>
                        <legend><font face="Verdana" size="2"><strong style="padding-bottom: 10px">Search Result</strong></font></legend>
                        <br />
                        <div>
                            @if (Model.reqMstList != null && Model.reqMstList.Any())
                            {
                                <table cellspacing="0" rules="all" border="1" id="gvActivationRequest" style="width:90%;border-collapse:collapse;">
                                    <tr style="background-color:#CCE4F5;font-weight:bold;height:20px;">
                                        <th scope="col">Request Date</th>
                                        <th scope="col">Ticket #</th>
                                        <th scope="col">Service Name</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Responsible Team</th>
                                        <th scope="col">Assigned To</th>
                                        <th scope="col">Comments</th>
                                    </tr>
                                    @foreach (ActivationReqMasterModel activationReq in Model.reqMstList)
                                    {

                                        <tr style="color:Black;height:18px;">
                                            <td>
                                                <span id="" style="display:inline-block;width:75px;">@activationReq.ticketCreateDate</span>
                                            </td>
                                            <td style="white-space:nowrap;">
                                                <a id="" href="/ActivationExecution/Execution?reqticketno=@activationReq.ticketNo" style="display:inline-block;width:110px;" target="_blank">@activationReq.ticketNo</a>
                                            </td>
                                            <td>
                                                <span id="" style="display:inline-block;width:120px;">@activationReq.serviceName</span>
                                            </td>
                                            <td>
                                                <span id="" style="display:inline-block;width:120px;">@activationReq.ticketStatus</span>
                                            </td>
                                            <td style="white-space:nowrap;">
                                                <span id="" style="display:inline-block;width:50px;">@activationReq.activationTeam</span>
                                            </td>
                                            <td style="white-space:nowrap;">
                                                <span id="" style="display:inline-block;width:80px;">@activationReq.ticketAssignUser</span>
                                            </td>
                                            <td>
                                                <span id="" style="display:inline-block;width:100px;">@activationReq.comments</span>
                                            </td>
                                        </tr>
                                    }
                                </table>
                            }
                            </div>
                        <br />
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td align="left" colspan="4">
                    &nbsp;
                </td>
            </tr>
        </table>
</form>